allowBuilds:
  '@parcel/watcher': true
  esbuild: true
minimumReleaseAgeExclude:
  - '@eddeee888/gcg-server-config@0.0.0-pr466-run387-1-20260809063344'
  - '@eddeee888/gcg-typescript-resolver-files@0.0.0-pr466-run387-1-20260809063344'
