name: CI

on:
  pull_request:
    branches:
      - master

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  node-version: '22.x'

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: pnpm/setup@v2

      - name: Codegen & check
        run: ./bin/codegen-check.sh

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm prettier . --list-different

      - name: Test
        run: pnpm test:once
